# Use an OpenJDK base image with both JDK and JRE
FROM openjdk:21-slim

# Set the working directory inside the container
WORKDIR /app

# Command to run the Java program (will be overwritten by `docker exec`)
CMD ["bash"]
